In [6]:
# retirando espaços em branco e caracteres especiais

# -*-coding: UTF-8 -*-
import pandas as pd
import numpy as np
import csv
import sys

# dataRem1 = pd.read_csv('/home/crislanio.macedo/DADOSABERTOS/Dados Abertos/dados_servidores/2017/201701_Servidores/20170131_Remuneracao.csv', delimiter="\t", encoding="ISO-8859-9", low_memory=False)
# dataRem2 = pd.read_csv('/home/crislanio.macedo/DADOSABERTOS/Dados Abertos/dados_servidores/2017/201701_Servidores/20170131_NovaRemuneracao.csv', delimiter=",", encoding="ISO-8859-9", low_memory=False)

dataHonor = pd.read_csv('/home/crislanio.macedo/DADOSABERTOS/Dados Abertos/dados_servidores/2017/201701_Servidores/20170131_Honorarios(Jetons).csv', delimiter="t", encoding="ISO-8859-9", low_memory=False)


# # Resumo das variáveis até o momento.Escolhendo as colunas para colocar em outro csv
# csvTable = data[['COD_UORG_LOTACAO','UORG_LOTACAO', 'COD_ORG_LOTACAO', 'ORG_LOTACAO', 'ORGSUP_LOTACAO','COD_ORGSUP_LOTACAO' ]]
# csvTable.info()

In [7]:
dataHonor.columns

Index(['ANO\tMES\tID_SERVIDOR_PORTAL\tCPF\tNOME\tEMPRESA\tVALOR'], dtype='object')

In [15]:
print(dataRem2.shape)
dataRem2.head(3)

(589074, 37)

,Unnamed: 0,ANO,MES,ID_SERVIDOR_PORTAL,CPF,NOME,REMUNERACAO_BASICA_BRUTA_REAIS,REMUNERACAO_BASICA_BRUTA_DOLLAR,ABATE_TETO_REAIS,ABATE_TETO_DOLLAR,...,DEMAIS_DEDUCOES_DOLLAR,REMUNERACAO_APOS_DEDUCOES_OBRIGATORIAS_REAIS,REMUNERACAO_APOS_DEDUCOES_OBRIGATORIAS_DOLLAR,VERBAS_INDENIZATORIAS_REGISTRADAS_EM_SISTEMAS_DE_PESSOAL_CIVIL_REAIS,VERBAS_INDENIZATORIAS_REGISTRADAS_EM_SISTEMAS_DE_PESSOAL_CIVIL_DOLLAR,VERBAS_INDENIZATORIAS_REGISTRADAS_EM_SISTEMAS_DE_PESSOAL_MILITAR_REAIS,VERBAS_INDENIZATORIAS_REGISTRADAS_EM_SISTEMAS_DE_PESSOAL_MILITAR_DOLLAR,TOTAL_DE_VERBAS_INDENIZATORIAS_REAIS,TOTAL_DE_VERBAS_INDENIZATORIAS_DOLLAR,TOTAL_DE_HONORARIOS_JETONS
0,0,2017,1,1000000,***.787.200-**,PAULO MARTINS SOARES,"7332,99","0,00","0,00","0,00",...,"0,00","5842,07","0,00","803,65","0,00","0,00","0,00","803,65","0,00","0,00"
1,1,2017,1,1000001,***.600.796-**,ANALIA BATISTA,"9607,00","0,00","0,00","0,00",...,"0,00","9709,57","0,00","1562,53","0,00","0,00","0,00","1562,53","0,00","0,00"
2,2,2017,1,1000002,***.124.863-**,ARY DE NOROES FILHO,"6313,85","0,00","0,00","0,00",...,"0,00","5942,85","0,00","817,93","0,00","0,00","0,00","817,93","0,00","0,00"

In [13]:
print(dataRem1.shape)
dataRem1.head(3)

(589074, 36)

,ANO,MES,ID_SERVIDOR_PORTAL,CPF,NOME,REMUNERAÇÃO BÁSICA BRUTA (R$),REMUNERAÇÃO BÁSICA BRUTA (U$),ABATE-TETO (R$),ABATE-TETO (U$),GRATIFICAÇÃO NATALINA (R$),...,DEMAIS DEDUÇÕES (U$),REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (R$),REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (U$),VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (R$)(*),VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (U$)(*),VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (R$)(*),VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (U$)(*),TOTAL DE VERBAS INDENIZATÓRIAS (R$)(*),TOTAL DE VERBAS INDENIZATÓRIAS (U$)(*),TOTAL DE HONORÁRIOS (JETONS)
0,2017,1,1000000,***.787.200-**,PAULO MARTINS SOARES,"7332,99","0,00","0,00","0,00","0,00",...,"0,00","5842,07","0,00","803,65","0,00","0,00","0,00","803,65","0,00","0,00"
1,2017,1,1000001,***.600.796-**,ANALIA BATISTA,"9607,00","0,00","0,00","0,00","0,00",...,"0,00","9709,57","0,00","1562,53","0,00","0,00","0,00","1562,53","0,00","0,00"
2,2017,1,1000002,***.124.863-**,ARY DE NOROES FILHO,"6313,85","0,00","0,00","0,00","0,00",...,"0,00","5942,85","0,00","817,93","0,00","0,00","0,00","817,93","0,00","0,00"